services:
  backend:
    build:
      context: ./backend
    container_name: cep-backend
    expose:
      - "3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: cep-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped